# Generated by Django 5.2.1 on 2025-05-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_car_showroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='nophoto.jpg', null=True, upload_to='cars/'),
        ),
    ]
