# Generated by Django 5.2.1 on 2025-05-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_car_showroom', '0003_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='cars/nophoto.jpg', upload_to='cars/'),
        ),
    ]
