# Generated by Django 5.2.1 on 2025-05-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_car_showroom', '0004_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
