# Generated by Django 5.2.1 on 2025-05-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_car_showroom', '0005_cart_is_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
