# Generated by Django 5.2.1 on 2025-05-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_car_showroom', '0006_cart_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_id',
            field=models.BigIntegerField(),
        ),
    ]
