# Generated by Django 5.2.1 on 2025-05-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_car_showroom', '0008_delete_faq_alter_car_brand_alter_car_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
